/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.update;

import hotelmanagement.dashboard_main.DashboardStaff;
import hotelmanagement.entity.dba_connection;
import java.text.ParseException;
import java.sql.Date;

import java.time.format.*;
import java.util.logging.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.text.MaskFormatter;
import java.text.SimpleDateFormat;
/**
 *
 * @author dell
 */
public class UpdateInvoiceForm extends javax.swing.JFrame {

    /**
     * Creates new form AddRoomForm
     */
    private DashboardStaff parent;
    public UpdateInvoiceForm() {
        setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
        MaskFormatter date;
        try {
            date = new MaskFormatter ("##/##/####");
            date.setPlaceholderCharacter('_');
            ftxtDayCreated.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date)); 
            ftxtDayStarted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
            ftxtDayEnded.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
            ftxtDayPaid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
    public UpdateInvoiceForm(DashboardStaff parent){
        setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
        MaskFormatter date;
        try {
            date = new MaskFormatter ("##/##/####");
            date.setPlaceholderCharacter('_');
            ftxtDayCreated.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date)); 
            ftxtDayStarted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
            ftxtDayEnded.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
            ftxtDayPaid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        this.parent = parent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtInvoiceID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRoomID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        ftxtDayCreated = new javax.swing.JFormattedTextField();
        ftxtDayStarted = new javax.swing.JFormattedTextField();
        ftxtDayEnded = new javax.swing.JFormattedTextField();
        ftxtDayPaid = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnBackInvoice = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Update Invoice");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Invoice ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Room ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Staff ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Day created");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Day started");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Day ended");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Day paid");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Payment status");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Service ID");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Total");

        ftxtDayCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDayCreatedActionPerformed(evt);
            }
        });

        ftxtDayEnded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDayEndedActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Customer ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtServiceID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(ftxtDayCreated)
                    .addComponent(ftxtDayStarted)
                    .addComponent(ftxtDayEnded)
                    .addComponent(ftxtDayPaid)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtStatus))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtServiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtDayCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ftxtDayStarted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ftxtDayEnded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ftxtDayPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBackInvoice.setText("Back");
        btnBackInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackInvoiceActionPerformed(evt);
            }
        });

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnCheck)
                .addGap(32, 32, 32)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBackInvoice)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnBackInvoice)
                    .addComponent(btnCheck))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxtDayEndedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDayEndedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtDayEndedActionPerformed

    private void ftxtDayCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDayCreatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtDayCreatedActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        dba_connection connect = new dba_connection();
        String invoiceID = txtInvoiceID.getText();  // Thay "roomIdTextField" bằng tên của text field nhập mã phòng

        if (invoiceID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Room ID.");
            return;  // Dừng nếu không có mã phòng
        }

        try {
            // Tạo kết nối tới cơ sở dữ liệu
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);

            // Truy vấn cơ sở dữ liệu để tìm phòng theo Room ID
            String query = "SELECT * FROM HOADON WHERE MAHD = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, invoiceID);
            // Thực hiện truy vấn và lấy kết quả
            ResultSet rs = pst.executeQuery();
                // Lấy dữ liệu từ kết quả truy vấn và điền vào các trường thông tin
                
            if (rs.next()){
                String customerID = rs.getString("MAKH");
                String madvp = rs.getString("MADVP");
                String madvti = rs.getString("MADVTI");
                String mafb = rs.getString("MAFB");
                String nguoiXacNhan = rs.getString("NGUOIXACNHAN");
                Date ngayTao = rs.getDate("NGAYTAO");
                Date ngayBD = rs.getDate("NGAYBD");
                Date ngayKT = rs.getDate("NGAYKT");
                Date ngayThanhToan = rs.getDate("NGAYTHANHTOAN");
                int tongTien = rs.getInt("TONGTIEN");
                String tinhTrangTT = rs.getString("TINHTRANGTT");
                int slsd = rs.getInt("SLSD");
                
                txtCustomerID.setText(customerID);
                txtRoomID.setText(madvp);
                txtServiceID.setText(madvti);              
                txtStaffID.setText(nguoiXacNhan);
                ftxtDayCreated.setText(ngayTao != null ? sdf.format(ngayTao) : "");
                ftxtDayStarted.setText(ngayBD != null ? sdf.format(ngayBD) : "");
                ftxtDayEnded.setText(ngayKT != null ? sdf.format(ngayKT) : "");
                ftxtDayPaid.setText(ngayThanhToan != null ? sdf.format(ngayThanhToan) : "");
                txtTotal.setText(String.valueOf(tongTien));
                txtStatus.setText(tinhTrangTT);              
            }
            else
                JOptionPane.showMessageDialog(null, "Invoice not found.");
            
            
            pst.close();
            con.close();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Input format from text fields (dd/MM/yyyy)
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
        // Output format for database (yyyy-MM-dd)
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");

        dba_connection connect = new dba_connection();
        String invoiceID = txtInvoiceID.getText();

        if (invoiceID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Room ID.");
            return;
        }

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);

            String query = "UPDATE HOADON SET MAKH = ?, MADVP = ?, MADVTI = ?, NGUOIXACNHAN = ?, " +
                          "NGAYTAO = TO_DATE(?, 'YYYY-MM-DD'), NGAYBD = TO_DATE(?, 'YYYY-MM-DD'), " +
                          "NGAYKT = TO_DATE(?, 'YYYY-MM-DD'), NGAYTHANHTOAN = TO_DATE(?, 'YYYY-MM-DD'), " +
                          "TONGTIEN = ?, TINHTRANGTT = ? WHERE MAHD = ?";

            PreparedStatement pst = con.prepareStatement(query);

            // Set string parameters
            pst.setString(1, txtCustomerID.getText());
            pst.setString(2, txtRoomID.getText());
            pst.setString(3, txtServiceID.getText());           
            pst.setString(4, txtStaffID.getText());

            
            try {
                // NGAYTAO
                String ngayTaoStr = ftxtDayCreated.getText();
                pst.setString(5, ngayTaoStr.isEmpty() ? null : 
                    outputFormat.format(inputFormat.parse(ngayTaoStr)));

                // NGAYBD
                String ngayBDStr = ftxtDayStarted.getText();
                pst.setString(6, ngayBDStr.isEmpty() ? null : 
                    outputFormat.format(inputFormat.parse(ngayBDStr)));

                // NGAYKT
                String ngayKTStr = ftxtDayEnded.getText();
                pst.setString(7, ngayKTStr.isEmpty() ? null : 
                    outputFormat.format(inputFormat.parse(ngayKTStr)));

                // NGAYTHANHTOAN
                String ngayThanhToanStr = ftxtDayPaid.getText();
                pst.setString(8, ngayThanhToanStr.isEmpty() ? null : 
                    outputFormat.format(inputFormat.parse(ngayThanhToanStr)));
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Invalid date format. Please use dd/MM/yyyy");
                return;
            }

            // Set remaining parameters
            String totalStr = txtTotal.getText();
            pst.setInt(9, totalStr.isEmpty() ? 0 : Integer.parseInt(totalStr));
            pst.setString(10, txtStatus.getText());
            pst.setString(11, invoiceID);

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Invoice updated successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Invoice not found.");
            }

            pst.close();
            con.close();

        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackInvoiceActionPerformed
        parent.autoReloadInvoice();
        this.dispose();
    }//GEN-LAST:event_btnBackInvoiceActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackInvoice;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JFormattedTextField ftxtDayCreated;
    private javax.swing.JFormattedTextField ftxtDayEnded;
    private javax.swing.JFormattedTextField ftxtDayPaid;
    private javax.swing.JFormattedTextField ftxtDayStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtInvoiceID;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
