/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.Login_Signup;

import hotelmanagement.entity.dba_connection;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.*;
import java.util.logging.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.text.MaskFormatter;
import java.text.SimpleDateFormat;



/**
 *
 * @author 84352
 */
public class Client_Signup extends javax.swing.JFrame {

    /**
     * Creates new form client_
     */
    public Client_Signup() {
        initComponents();
        MaskFormatter date;
        try {
            date = new MaskFormatter ("##/##/####");
            date.setPlaceholderCharacter('_');
            Date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(date));            
        } catch (ParseException ex) {
            Logger.getLogger(Client_Signup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Fullname_txt = new javax.swing.JTextField();
        CCCD_txt = new javax.swing.JTextField();
        Sdt_txt = new javax.swing.JTextField();
        Address_txt = new javax.swing.JTextField();
        Email_txt = new javax.swing.JTextField();
        Pass_txt = new javax.swing.JPasswordField();
        Cancel_button = new javax.swing.JButton();
        Signup_button = new javax.swing.JButton();
        Date = new javax.swing.JFormattedTextField();
        GenderBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 121, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Sign up");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Fullname: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ID: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Address: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Phone:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Gender: ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Password:");

        CCCD_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Sdt_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Address_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Email_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Pass_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Cancel_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cancel_button.setText("Cancel");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });

        Signup_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Signup_button.setText("Signup now");
        Signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_buttonActionPerformed(evt);
            }
        });

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(Cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Fullname_txt)
                        .addComponent(CCCD_txt)
                        .addComponent(Sdt_txt)
                        .addComponent(Address_txt)
                        .addComponent(Email_txt)
                        .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(Pass_txt)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Fullname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CCCD_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Sdt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed

    }//GEN-LAST:event_DateActionPerformed

    private void Cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        new Client_Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void Signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_buttonActionPerformed
        try {
            String input = Date.getText();
            dba_connection connect = new dba_connection();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(input, format);
    // Xét các ô bắt buộc phải điền

            if(Fullname_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                Fullname_txt.requestFocus();
            }
            else if(Date.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                Date.requestFocus();
            }
            else if(CCCD_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                CCCD_txt.requestFocus();
            }
            else if(Sdt_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                Sdt_txt.requestFocus();
            }
            else if(Address_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                Address_txt.requestFocus();
            }
            else if(Pass_txt.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All filed value is mandatory");
                Pass_txt.requestFocus();
            }

    //CCCD và SDT phải là số
            else if(!CCCD_txt.getText().matches("\\d+")){
                JOptionPane.showMessageDialog(this, "ID must be number");
            }

            else if(!Sdt_txt.getText().matches("\\d+")){
                JOptionPane.showMessageDialog(this, "Phone number must be number");
            }
    // CCCD phải là 12 sô và SDT từ 10 đến 11 số
            else if(CCCD_txt.getText().length() != 12){
                JOptionPane.showMessageDialog(this, "ID must have 12 characters");
            }     
            else if(Sdt_txt.getText().length() < 10 || Sdt_txt.getText().length() > 11){           
                JOptionPane.showMessageDialog(this, "Phone number must have 10-12 characters");
            }
            else{
                Class.forName(connect.driver);
                PreparedStatement pst = null;

                Connection con = DriverManager.getConnection(connect.url, connect.username,connect.password);
                pst = con.prepareStatement("Select * from " + connect.username + ".KHACHHANG where SDT = ?");
                pst.setString(1, Sdt_txt.getText());

                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showConfirmDialog(this, "This phone number is already exists");
                }else{
                    String gender = (String) GenderBox.getSelectedItem();
                        
                    //Dich tieng anh thanh tieng viet de database hieu
                    gender = gender.equals("Male") ? "Nam" : gender.equals("Female") ? "Nu" : gender;
                        
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date parsedDate = sdf.parse(Date.getText());
                    java.sql.Date sqlDate = new java.sql.Date(parsedDate.getTime());

                    pst = con.prepareStatement("Insert into " + connect.username + ".KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL) VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                    pst.setString(1, Fullname_txt.getText());
                    pst.setString(2, Pass_txt.getText());
                    pst.setString(3, CCCD_txt.getText());
                    pst.setString(4, Sdt_txt.getText());
                    pst.setDate(5, sqlDate); // <-- dùng đúng loại
                    pst.setString(6, gender);
                    pst.setString(7, Address_txt.getText());
                    pst.setString(8, Email_txt.getText());

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Sign up successfully!");
                    new Client_Login().setVisible(true);
                    Client_Signup.this.setVisible(false);    
                }
                }
        }catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(Client_Signup.class.getName()).log(Level.SEVERE, null, ex);               
        }catch (DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Invalid date");
            Date.requestFocus();
        }
    }//GEN-LAST:event_Signup_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_txt;
    private javax.swing.JTextField CCCD_txt;
    private javax.swing.JButton Cancel_button;
    private javax.swing.JFormattedTextField Date;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JTextField Fullname_txt;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JPasswordField Pass_txt;
    private javax.swing.JTextField Sdt_txt;
    private javax.swing.JButton Signup_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
