BEGIN
  FOR proc IN (
    SELECT object_name
    FROM user_objects
    WHERE object_type = 'PROCEDURE'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PROCEDURE ' || proc.object_name;
  END LOOP;
END;
/

BEGIN
  FOR trig IN (
    SELECT trigger_name FROM user_triggers
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER ' || trig.trigger_name;
  END LOOP;
END;
/

BEGIN
  FOR seq IN (
    SELECT sequence_name FROM user_sequences
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq.sequence_name;
  END LOOP;
END;
/

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- TẠO BẢNG DỮ LIỆU VÀ KHOÁ NGOẠI
CREATE TABLE NHANVIEN(
    MANV CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) UNIQUE,
    SDT CHAR(11) UNIQUE,
    NGAYSINH DATE,
    GIOITINH CHAR(10),
    DIACHI CHAR(50),
    EMAIL CHAR(20),
    LUONG NUMBER(9),
    CHUCVU CHAR(10),
    NGAYVAOLAM DATE,
    MAQL CHAR(5),
    
    -- KHOÁ NGOẠI
    CONSTRAINT FK_MAQL FOREIGN KEY (MAQL) REFERENCES NHANVIEN(MANV) 
)
/

CREATE TABLE KHACHHANG(
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) NOT NULL UNIQUE,
    SDT CHAR(11) NOT NULL UNIQUE,
    NGAYSINH DATE,
    GIOITINH CHAR(5),
    DIACHI CHAR(100),
    EMAIL CHAR(50)
)
/

CREATE TABLE DVPHONG(
    MADVP CHAR(4) PRIMARY KEY,
    LOAIPHONG CHAR(50), 
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG NVARCHAR2(100) NOT NULL
)
/

CREATE TABLE DVTIENICH(
    MADVTI CHAR(5) PRIMARY KEY,
    TENDVTI CHAR(100),
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG NVARCHAR2(100)
)   
/

CREATE TABLE FEEDBACK(
    MAFB CHAR(5) PRIMARY KEY,
    NOIDUNG NVARCHAR2(200),
    NGAYDANG DATE
)
/

CREATE TABLE HOADON(
    MAHD CHAR(5) PRIMARY KEY, 
    MAKH CHAR(5) NOT NULL,
    MADVP CHAR(4),
    MADVTI CHAR(5),
    MAFB CHAR(5),
    NGUOIXACNHAN CHAR(5),
    NGAYTAO DATE, 
    NGAYBD DATE,
    NGAYKT DATE,
    NGAYTHANHTOAN DATE,
    TONGTIEN NUMBER(9) NOT NULL,
    TINHTRANGTT NVARCHAR2(50),
    SLSD NUMBER(2),
    
    --KHOÁ NGOẠI
    CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_MADVP FOREIGN KEY (MADVP) REFERENCES DVPHONG(MADVP),
    CONSTRAINT FK_MADVTI FOREIGN KEY (MADVTI) REFERENCES DVTIENICH(MADVTI),
    CONSTRAINT FK_MAFB FOREIGN KEY (MAFB) REFERENCES FEEDBACK(MAFB),
    CONSTRAINT FK_NGUOIXN FOREIGN KEY (NGUOIXACNHAN) REFERENCES NHANVIEN(MANV)
)
/
--TRIGGER
----------------------------------------------------------------
--1 NHẬP DỮ LIỆU SẼ TỰ ĐỘNG NHẬP KHOÁ THEO THỨ TỰ
----------------------------------------------------------------
--NHÂN VIÊN
CREATE SEQUENCE SEQ_MANV
START WITH 1
INCREMENT BY 1
NOCACHE;
/

CREATE OR REPLACE TRIGGER AUTO_NHANVIEN
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    :NEW.MANV := 'NV' || LPAD(SEQ_MANV.NEXTVAL, 3, '0');
END;
/

--KHÁCH HÀNG
CREATE SEQUENCE SEQ_MAKH
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_KHACHHANG
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    :NEW.MAKH := 'KH' || LPAD(SEQ_MAKH.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ PHÒNG
CREATE SEQUENCE SEQ_MADVP
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_MAPHONG
BEFORE INSERT ON DVPHONG
FOR EACH ROW
BEGIN
    :NEW.MADVP := 'P' || LPAD(SEQ_MADVP.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ TIỆN ÍCH
CREATE SEQUENCE SEQ_MADVTI
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_DVTIENICH
BEFORE INSERT ON DVTIENICH
FOR EACH ROW
BEGIN
    :NEW.MADVTI := 'TI' || LPAD(SEQ_MADVTI.NEXTVAL, 3, '0');
END;
/

--FEEDBACK
CREATE SEQUENCE SEQ_MAFB
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_FEEDBACK
BEFORE INSERT ON FEEDBACK
FOR EACH ROW
BEGIN
    :NEW.MAFB := 'FB' || LPAD(SEQ_MAFB.NEXTVAL, 3, '0');
END;
/

--HOÁ ĐƠN
CREATE SEQUENCE SEQ_MAHD
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_HOADON
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    :NEW.MAHD := 'HD' || LPAD(SEQ_MAHD.NEXTVAL, 3, '0');
END;
/

----------------------------------------------------------------
--2 XỬ LÝ TIỀN HOÁ ĐƠN 
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER TONGTIENHOADON
BEFORE INSERT OR UPDATE ON HOADON
FOR EACH ROW
DECLARE 
    V_DONGIA_PHONG DVPHONG.DONGIA%TYPE;
    V_DONGIA_TIENICH DVTIENICH.DONGIA%TYPE;
BEGIN
    IF :NEW.MADVP IS NOT NULL THEN
        SELECT DONGIA INTO V_DONGIA_PHONG FROM DVPHONG WHERE MADVP = :NEW.MADVP;
        :NEW.SLSD := TRUNC(:NEW.NGAYKT) - TRUNC(:NEW.NGAYBD);
        :NEW.TONGTIEN := (V_DONGIA_PHONG * :NEW.SLSD);
    END IF;
    
    IF :NEW.MADVTI IS NOT NULL THEN
        SELECT DONGIA INTO V_DONGIA_TIENICH FROM DVTIENICH WHERE MADVTI = :NEW.MADVTI;
        :NEW.SLSD := TRUNC(:NEW.NGAYKT) - TRUNC(:NEW.NGAYBD);
        :NEW.TONGTIEN :=  (V_DONGIA_TIENICH * :NEW.SLSD);
    END IF;    
END;
/

----------------------------------------------------------------
--3 XỬ LÝ CẬP NHẬT PHÒNG
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER CAPNHATPHONG
AFTER INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.MADVP IS NOT NULL THEN
        UPDATE DVPHONG
        SET TINHTRANG = 'Occupied'
        WHERE MADVP = :NEW.MADVP;
    END IF;
END;
/

----------------------------------------------------------------
--3 XỬ LÝ NGÀY
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER NGAYTAO_HOADON
BEFORE INSERT ON HOADON 
FOR EACH ROW
BEGIN
    :NEW.NGAYTAO := SYSDATE;
END;
/
CREATE OR REPLACE TRIGGER NGAYTAO_FEEDBACK
BEFORE INSERT ON FEEDBACK 
FOR EACH ROW
BEGIN
    :NEW.NGAYDANG := SYSDATE;
END;
/

--DATASET--------------------------------------
--NHANVIEN
INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Nguyễn Văn An', 'pass123', '001234567890', '0912345678', TO_DATE('1990-05-01','YYYY-MM-DD'), 'Nam', 'Hà Nội', 'an.nguyen@gmail.com', 15000000, 'LE TAN', TO_DATE('2023-01-10','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Lê Thị Hoa', 'pass123', '001234567891', '0923456789', TO_DATE('1992-07-15','YYYY-MM-DD'), 'Nữ', 'TP.HCM', 'hoa.le@gmail.com', 18000000, 'QUAN LY', TO_DATE('2022-03-05','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Phạm Văn Bình', 'pass123', '001234567892', '0934567890', TO_DATE('1995-09-20','YYYY-MM-DD'), 'Nam', 'Đà Nẵng', 'binh.pham@gmail.com', 14000000, 'LE TAN', TO_DATE('2023-06-01','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Ngô Thị Lan', 'pass123', '001234567893', '0945678901', TO_DATE('1991-12-01','YYYY-MM-DD'), 'Nữ', 'Hải Phòng', 'lan.ngo@gmail.com', 16000000, 'KE TOAN', TO_DATE('2022-11-15','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Hoàng Minh Tuấn', 'pass123', '001234567894', '0956789012', TO_DATE('1988-03-11','YYYY-MM-DD'), 'Nam', 'Huế', 'tuan.hoang@gmail.com', 20000000, 'QUAN LY', TO_DATE('2021-09-01','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Trần Thị Mai', 'pass123', '001234567895', '0967890123', TO_DATE('1996-08-19','YYYY-MM-DD'), 'Nữ', 'Cần Thơ', 'mai.tran@gmail.com', 13500000, 'LE TAN', TO_DATE('2023-02-20','YYYY-MM-DD'), 'NV005');

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Đỗ Văn Hùng', 'pass123', '001234567896', '0978901234', TO_DATE('1993-10-10','YYYY-MM-DD'), 'Nam', 'Quảng Ninh', 'hung.do@gmail.com', 17000000, 'KE TOAN', TO_DATE('2022-05-10','YYYY-MM-DD'), 'NV005');

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Lý Thị Hồng', 'pass123', '001234567897', '0989012345', TO_DATE('1994-11-21','YYYY-MM-DD'), 'Nữ', 'Nha Trang', 'hong.ly@gmail.com', 15000000, 'LE TAN', TO_DATE('2023-04-25','YYYY-MM-DD'), 'NV005');

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Bùi Quang Dũng', 'pass123', '001234567898', '0990123456', TO_DATE('1990-01-30','YYYY-MM-DD'), 'Nam', 'Vũng Tàu', 'dung.bui@gmail.com', 19000000, 'QUAN LY', TO_DATE('2020-12-10','YYYY-MM-DD'), NULL);

INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'Hà Thị Hương', 'pass123', '001234567899', '0901234567', TO_DATE('1997-06-05','YYYY-MM-DD'), 'Nữ', 'Bắc Ninh', 'huong.ha@gmail.com', 14500000, 'LE TAN', TO_DATE('2023-07-15','YYYY-MM-DD'), 'NV009');
/

--KHACHHANG
INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Nguyễn Thị Hương', 'pass123', '012345678900', '0911111111', TO_DATE('1995-03-15','YYYY-MM-DD'), 'Nữ', 'Hà Nội', 'huong.nguyen@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Lê Văn Long', 'pass123', '012345678901', '0922222222', TO_DATE('1992-06-20','YYYY-MM-DD'), 'Nam', 'TP.HCM', 'long.le@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Trần Thị Mai', 'pass123', '012345678902', '0933333333', TO_DATE('1990-09-25','YYYY-MM-DD'), 'Nữ', 'Đà Nẵng', 'mai.tran@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Phạm Văn Đức', 'pass123', '012345678903', '0944444444', TO_DATE('1988-11-30','YYYY-MM-DD'), 'Nam', 'Nghệ An', 'duc.pham@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Đặng Thị Hạnh', 'pass123', '012345678904', '0955555555', TO_DATE('1994-01-10','YYYY-MM-DD'), 'Nữ', 'Hải Phòng', 'hanh.dang@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Bùi Văn Lâm', 'pass123', '012345678905', '0966666666', TO_DATE('1991-04-12','YYYY-MM-DD'), 'Nam', 'Nam Định', 'lam.bui@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Hoàng Thị Thu', 'pass123', '012345678906', '0977777777', TO_DATE('1993-07-07','YYYY-MM-DD'), 'Nữ', 'Bình Dương', 'thu.hoang@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Ngô Văn Kiên', 'pass123', '012345678907', '0988888888', TO_DATE('1987-02-14','YYYY-MM-DD'), 'Nam', 'Lâm Đồng', 'kien.ngo@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Lý Thị Như', 'pass123', '012345678908', '0999999999', TO_DATE('1996-10-18','YYYY-MM-DD'), 'Nữ', 'Khánh Hòa', 'nhu.ly@gmail.com');

INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'Tạ Văn Hậu', 'pass123', '012345678909', '0900000000', TO_DATE('1989-12-22','YYYY-MM-DD'), 'Nam', 'Quảng Ninh', 'hau.ta@gmail.com');
/

--DVPHONG
INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đơn', 'Phòng đơn có giường 1m6, điều hòa', 500000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đôi', 'Phòng đôi 2 giường, có tivi và bàn làm việc', 800000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có ban công và bồn tắm', 1500000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng gia đình', 'Phòng rộng cho 4 người, có bếp mini', 1200000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiêu chuẩn có wifi và tủ lạnh mini', 600000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đơn', 'Phòng đơn có cửa sổ lớn, view đẹp', 550000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đôi', 'Phòng đôi sát biển, điều hòa trung tâm', 850000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 1600000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiện nghi cơ bản, gần sảnh chính', 650000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng gia đình', 'Phòng lớn, có 2 giường đôi và khu sinh hoạt', 1250000, N'Occupied');
/

--DVTIENICH
INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Giặt ủi', 'Dịch vụ giặt ủi trong ngày', 30000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Đưa đón sân bay', 'Đưa đón sân bay bằng xe 7 chỗ', 250000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Bữa sáng', 'Bữa sáng buffet tại nhà hàng', 100000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Gọi món tại phòng', 'Phục vụ đồ ăn tận phòng', 50000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Spa', 'Gói massage thư giãn 60 phút', 300000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Cho thuê xe máy', 'Thuê xe máy nguyên ngày', 120000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng Gym', 'Sử dụng phòng Gym toàn thời gian', 50000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Hồ bơi', 'Sử dụng hồ bơi ngoài trời', 40000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Karaoke', 'Thuê phòng Karaoke theo giờ', 150000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Giữ hành lý', 'Gửi hành lý miễn phí', 0, 'Available');
/

--FEEDBACK
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Dịch vụ rất tốt, nhân viên thân thiện.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Phòng sạch sẽ, đầy đủ tiện nghi.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Tôi rất hài lòng với trải nghiệm tại khách sạn.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Thức ăn ngon, phục vụ nhanh');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Cần cải thiện wifi, hơi yếu ở phòng tôi.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Giá cả hợp lý, vị trí thuận tiện.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Đặt phòng nhanh chóng, thủ tục đơn giản.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Phòng view đẹp, thích hợp nghỉ dưỡng.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Spa rất chuyên nghiệp và thư giãn.');
INSERT INTO FEEDBACK (NOIDUNG) VALUES (N'Sẽ quay lại vào lần sau. Cảm ơn khách sạn!');
/

--HOADON--
--phong
INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH001', 'NV001', 'P001', NULL, NULL, SYSDATE - 5, SYSDATE + 2, SYSDATE - 5, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH002', 'NV002', 'P002', NULL, 'FB001', SYSDATE - 3, SYSDATE + 2, SYSDATE - 3, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH003', 'NV003', 'P002', NULL, NULL, SYSDATE + 3, SYSDATE + 5, SYSDATE + 1, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH004', 'NV004', 'P004', NULL, 'FB002', SYSDATE - 8, SYSDATE + 3, SYSDATE - 8, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH005', 'NV005', 'P004', NULL, NULL, SYSDATE + 5, SYSDATE + 8, SYSDATE + 4, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH006', 'NV006', 'P007', NULL, NULL, SYSDATE - 4, SYSDATE - 1, SYSDATE - 4, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH007', 'NV007', 'P007', NULL, 'FB003', SYSDATE + 6, SYSDATE + 9, SYSDATE + 5, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH008', 'NV008', 'P009', NULL, NULL, SYSDATE - 2, SYSDATE + 1, SYSDATE - 2, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH009', 'NV009', 'P009', NULL, NULL, SYSDATE + 2, SYSDATE + 4, SYSDATE + 1, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH010', 'NV010', 'P010', NULL, 'FB004', SYSDATE - 10, SYSDATE - 5, SYSDATE - 10, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH001', 'NV002', 'P010', NULL, NULL, SYSDATE + 4, SYSDATE + 7, SYSDATE + 2, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH002', 'NV003', 'P002', NULL, 'FB005', SYSDATE - 6, SYSDATE - 3, SYSDATE - 6, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH003', 'NV004', 'P003', NULL, NULL, SYSDATE + 7, SYSDATE + 10, SYSDATE + 6, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH004', 'NV005', 'P004', NULL, 'FB006', SYSDATE - 1, SYSDATE + 2, SYSDATE - 1, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH005', 'NV006', 'P005', NULL, NULL, SYSDATE + 1, SYSDATE + 4, SYSDATE, 'Chưa thanh toán');

--tien ich
INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH001', 'NV001', NULL, 'TI001', NULL, SYSDATE - 5, SYSDATE + 2, SYSDATE - 5, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH002', 'NV002', NULL, 'TI002', 'FB001', SYSDATE - 3, SYSDATE + 2, SYSDATE - 3, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH003', 'NV003', NULL, 'TI003', NULL, SYSDATE + 3, SYSDATE + 5, SYSDATE + 1, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH004', 'NV004', NULL, 'TI004', 'FB002', SYSDATE - 8, SYSDATE + 3, SYSDATE - 8, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH005', 'NV005', NULL, 'TI005', NULL, SYSDATE + 6, SYSDATE + 8, SYSDATE + 4, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH006', 'NV006', NULL, 'TI006', NULL, SYSDATE - 4, SYSDATE - 1, SYSDATE - 4, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH007', 'NV007', NULL, 'TI007', 'FB003', SYSDATE + 7, SYSDATE + 9, SYSDATE + 5, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH008', 'NV008', NULL, 'TI008', NULL, SYSDATE - 2, SYSDATE + 1, SYSDATE - 2, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH009', 'NV009', NULL, 'TI009', NULL, SYSDATE + 2, SYSDATE + 4, SYSDATE + 1, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH010', 'NV010', NULL, 'TI010', 'FB004', SYSDATE - 10, SYSDATE - 5, SYSDATE - 10, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH001', 'NV002', NULL, 'TI001', NULL, SYSDATE + 5, SYSDATE + 7, SYSDATE + 2, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH002', 'NV003', NULL, 'TI002', 'FB005', SYSDATE - 6, SYSDATE - 3, SYSDATE - 6, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH003', 'NV004', NULL, 'TI003', NULL, SYSDATE + 9, SYSDATE + 10, SYSDATE + 6, 'Chưa thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH004', 'NV005', NULL, 'TI004', 'FB006', SYSDATE - 1, SYSDATE + 2, SYSDATE - 1, 'Đã thanh toán');

INSERT INTO HOADON (MAKH, NGUOIXACNHAN, MADVP, MADVTI, MAFB, NGAYBD, NGAYKT, NGAYTHANHTOAN, TINHTRANGTT)
VALUES ('KH005', 'NV006', NULL, 'TI005', NULL, SYSDATE + 3, SYSDATE + 4, SYSDATE, 'Chưa thanh toán');
/
COMMIT;


