-- TẠO BẢNG DỮ LIỆU VÀ KHOÁ NGOẠI
CREATE TABLE NHANVIEN(
    MANV CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) UNIQUE,
    SDT CHAR(11) UNIQUE,
    NGAYSINH DATE,
    GIOITINH CHAR(10),
    DIACHI CHAR(50),
    EMAIL CHAR(20),
    LUONG NUMBER(9) NOT NULL,
    CHUCVU CHAR(10) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    MAQL CHAR(5),
    
    -- KHOÁ NGOẠI
    CONSTRAINT FK_MAQL FOREIGN KEY (MAQL) REFERENCES NHANVIEN(MANV) 
)

CREATE TABLE KHACHHANG(
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) NOT NULL UNIQUE,
    SDT CHAR(11) NOT NULL UNIQUE,
    NGAYSINH DATE NOT NULL,
    GIOITINH CHAR(5) NOT NULL,
    DIACHI CHAR(100),
    EMAIL CHAR(50)
)

CREATE TABLE DVPHONG(
    MADVP CHAR(4) PRIMARY KEY,
    LOAIPHONG CHAR(50), 
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG CHAR(100) NOT NULL
)

CREATE TABLE DVTIENICH(
    MADVTI CHAR(5) PRIMARY KEY,
    TENDVTI CHAR(100),
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG CHAR(100)
)   

CREATE TABLE FEEDBACK(
    MAFB CHAR(5) PRIMARY KEY,
    NOIDUNG CHAR(200) NOT NULL,
    NGAYDANG DATE NOT NULL
)

CREATE TABLE HOADON(
    MAHD CHAR(5) PRIMARY KEY, 
    MAKH CHAR(5) NOT NULL,
    MADVP CHAR(4),
    MADVTI CHAR(5),
    MAFB CHAR(5),
    NGUOIXACNHAN CHAR(5),
    NGAYTAO DATE NOT NULL, 
    NGAYBD DATE NOT NULL,
    NGAYKT DATE NOT NULL,
    NGAYTHANHTOAN DATE,
    TONGTIEN NUMBER(9) NOT NULL,
    TINHTRANGTT CHAR(50),
    SLSD NUMBER(2),
    
    --KHOÁ NGOẠI
    CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_MADVP FOREIGN KEY (MADVP) REFERENCES DVPHONG(MADVP),
    CONSTRAINT FK_MADVTI FOREIGN KEY (MADVTI) REFERENCES DVTIENICH(MADVTI),
    CONSTRAINT FK_MAFB FOREIGN KEY (MAFB) REFERENCES FEEDBACK(MAFB),
    CONSTRAINT FK_NGUOIXN FOREIGN KEY (NGUOIXACNHAN) REFERENCES NHANVIEN(MANV)
)
INSERT INTO HOADON(MAKH, MADVP, MADVTI, MAFB, NGUOIXACNHAN, NGAYTAO, NGAYBD, NGAYKT, NGAYTHANHTOAN, TONGTIEN, TINHTRANGTT, SLSD)
VALUES
('KH001', 'P001', 'DV001', 'FB001', 'NV001', TO_DATE('2024-01-10','YYYY-MM-DD'), TO_DATE('2024-01-12','YYYY-MM-DD'), TO_DATE('2024-01-15','YYYY-MM-DD'), TO_DATE('2024-01-16','YYYY-MM-DD'), 2500000, 'Paid', 3);
--TRIGGER
----------------------------------------------------------------
--1 NHẬP DỮ LIỆU SẼ TỰ ĐỘNG NHẬP KHOÁ THEO THỨ TỰ
----------------------------------------------------------------
--NHÂN VIÊN
CREATE SEQUENCE SEQ_MANV
START WITH 1
INCREMENT BY 1
NOCACHE;
/

CREATE OR REPLACE TRIGGER AUTO_NHANVIEN
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    :NEW.MANV := 'NV' || LPAD(SEQ_MANV.NEXTVAL, 3, '0');
END;
/

--KHÁCH HÀNG
CREATE SEQUENCE SEQ_MAKH
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_KHACHHANG
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    :NEW.MAKH := 'KH' || LPAD(SEQ_MAKH.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ PHÒNG
CREATE SEQUENCE SEQ_MADVP
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_MAPHONG
BEFORE INSERT ON DVPHONG
FOR EACH ROW
BEGIN
    :NEW.MADVP := 'P' || LPAD(SEQ_MADVP.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ TIỆN ÍCH
CREATE SEQUENCE SEQ_MADVTI
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_DVTIENICH
BEFORE INSERT ON DVTIENICH
FOR EACH ROW
BEGIN
    :NEW.MADVTI := 'TI' || LPAD(SEQ_MADVTI.NEXTVAL, 3, '0');
END;
/

--FEEDBACK
CREATE SEQUENCE SEQ_MAFB
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_FEEDBACK
BEFORE INSERT ON FEEDBACK
FOR EACH ROW
BEGIN
    :NEW.MAFB := 'FB' || LPAD(SEQ_MAFB.NEXTVAL, 3, '0');
END;
/

--HOÁ ĐƠN
CREATE SEQUENCE SEQ_MAHD
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_HOADON
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    :NEW.MAHD := 'HD' || LPAD(SEQ_MAHD.NEXTVAL, 3, '0');
END;
/

----------------------------------------------------------------
--2 XỬ LÝ TIỀN HOÁ ĐƠN 
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER TONGTIENHOADON
BEFORE INSERT OR UPDATE ON HOADON
FOR EACH ROW
DECLARE 
    V_DONGIA_PHONG DVPHONG.DONGIA%TYPE;
    V_DONGIA_TIENICH DVTIENICH.DONGIA%TYPE;
BEGIN
    IF :NEW.MADVP IS NOT NULL THEN
        SELECT DONGIA INTO V_DONGIA_PHONG FROM DVPHONG WHERE MADVP = :NEW.MADVP;
        :NEW.SLSD := TRUNC(:NEW.NGAYKT) - TRUNC(:NEW.NGAYBD);
        :NEW.TONGTIEN := (V_DONGIA_PHONG * :NEW.SLSD);
    END IF;
    
    IF :NEW.MADVTI IS NOT NULL THEN
        SELECT DONGIA INTO V_DONGIA_TIENICH FROM DVTIENICH WHERE MADVTI = :NEW.MADVTI;
        :NEW.SLSD := TRUNC(:NEW.NGAYKT) - TRUNC(:NEW.NGAYBD);
        :NEW.TONGTIEN :=  (V_DONGIA_TIENICH * :NEW.SLSD);
    END IF;    
END;

----------------------------------------------------------------
--3 XỬ LÝ CẬP NHẬT PHÒNG
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER CAPNHATPHONG
AFTER INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.MADVP IS NOT NULL THEN
        UPDATE DVPHONG
        SET TINHTRANG = 'DA DUOC DAT'
        WHERE MADVP = :NEW.MADVP;
    END IF;
END;
/

----------------------------------------------------------------
--3 XỬ LÝ NGÀY
----------------------------------------------------------------
CREATE OR REPLACE TRIGGER NGAYTAO_HOADON
BEFORE INSERT ON HOADON 
FOR EACH ROW
BEGIN
    :NEW.NGAYTAO := SYSDATE;
END;
/
CREATE OR REPLACE TRIGGER NGAYTAO_FEEDBACK
BEFORE INSERT ON FEEDBACK 
FOR EACH ROW
BEGIN
    :NEW.NGAYDANG := SYSDATE;
END;
/

--KIỂM TRA CÁC TRIGGER CÓ TRONG DBA
SELECT TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGER_TYPE, TRIGGERING_EVENT
FROM DBA_TRIGGERS
WHERE TABLE_NAME IN (SELECT TABLE_NAME FROM DBA_TABLES);
