/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement;

import hotelmanagement.RoomsManagement.Room;
import hotelmanagement.RoomsManagement.AddRoomForm;
import hotelmanagement.RoomsManagement.UpdateRoomForm;
import hotelmanagement.ServicesManagement.AddServiceForm;
import hotelmanagement.ServicesManagement.UpdateServiceForm;
import hotelmanagement.ServicesManagement.Service;
import hotelmanagement.InvoicesManagement.Invoice;
import hotelmanagement.InvoicesManagement.AddInvoiceForm;
import hotelmanagement.InvoicesManagement.UpdateInvoiceForm;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.table.*;


public class DashboardForm extends javax.swing.JFrame {

    ArrayList<Room> rooms = new ArrayList<>();
    ArrayList<Service> services = new ArrayList<>();
    ArrayList<Invoice> invoices = new ArrayList<>();
    public DashboardForm() {
        
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnRoomManagement = new javax.swing.JButton();
        btnServiceManagement = new javax.swing.JButton();
        btnInvoiceManagement = new javax.swing.JButton();
        CardLayout_Management = new javax.swing.JPanel();
        Rooms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        LbRoomManage = new javax.swing.JLabel();
        btnAddRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnBackRoom = new javax.swing.JButton();
        btnUpdateRoom = new javax.swing.JButton();
        btnReloadRoom = new javax.swing.JButton();
        Services = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        LbRoomManage1 = new javax.swing.JLabel();
        btnAddService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        btnBackService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();
        btnReloadService = new javax.swing.JButton();
        Invoices = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        LbRoomManage2 = new javax.swing.JLabel();
        btnAddInvoice = new javax.swing.JButton();
        btnDeleteInvoice = new javax.swing.JButton();
        btnBackInvoice = new javax.swing.JButton();
        btnUpdateInvoice = new javax.swing.JButton();
        btnReloadInVoice = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        btnRoomManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRoomManagement.setText("Room Management");
        btnRoomManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManagementActionPerformed(evt);
            }
        });

        btnServiceManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnServiceManagement.setText("Service Management");
        btnServiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceManagementActionPerformed(evt);
            }
        });

        btnInvoiceManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInvoiceManagement.setText("Invoice Management");
        btnInvoiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRoomManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServiceManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvoiceManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(btnRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btnServiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnInvoiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        CardLayout_Management.setLayout(new java.awt.CardLayout());

        Rooms.setBackground(new java.awt.Color(51, 0, 255));

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Type", "Describe", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRooms);
        tblRooms.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblRooms.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblRooms.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblRooms.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblRooms.getColumnModel().getColumn(4).setPreferredWidth(130);

        LbRoomManage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbRoomManage.setText("Room Management");

        btnAddRoom.setText("Add");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setText("Delete");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnBackRoom.setText("Back");
        btnBackRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomActionPerformed(evt);
            }
        });

        btnUpdateRoom.setText("Update");
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });

        btnReloadRoom.setText("Reload");
        btnReloadRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomsLayout = new javax.swing.GroupLayout(Rooms);
        Rooms.setLayout(RoomsLayout);
        RoomsLayout.setHorizontalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbRoomManage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RoomsLayout.createSequentialGroup()
                .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(RoomsLayout.createSequentialGroup()
                                .addComponent(btnReloadRoom)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)))
                    .addGroup(RoomsLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnAddRoom)
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdateRoom)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteRoom)
                        .addGap(28, 28, 28)
                        .addComponent(btnBackRoom)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RoomsLayout.setVerticalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LbRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReloadRoom)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBackRoom)
                    .addComponent(btnAddRoom)
                    .addComponent(btnUpdateRoom)
                    .addComponent(btnDeleteRoom))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Rooms, "card2");

        Services.setBackground(new java.awt.Color(102, 102, 255));

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Type", "Describe", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblServices);
        tblRooms.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblRooms.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblRooms.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblRooms.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblRooms.getColumnModel().getColumn(4).setPreferredWidth(130);

        LbRoomManage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbRoomManage1.setText("Service Management");

        btnAddService.setText("Add");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnDeleteService.setText("Delete");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        btnBackService.setText("Back");
        btnBackService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackServiceActionPerformed(evt);
            }
        });

        btnUpdateService.setText("Update");
        btnUpdateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServiceActionPerformed(evt);
            }
        });

        btnReloadService.setText("Reload");
        btnReloadService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicesLayout = new javax.swing.GroupLayout(Services);
        Services.setLayout(ServicesLayout);
        ServicesLayout.setHorizontalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LbRoomManage1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ServicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServicesLayout.createSequentialGroup()
                        .addGroup(ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ServicesLayout.createSequentialGroup()
                                .addComponent(btnReloadService)
                                .addGap(0, 574, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnAddService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackService)
                        .addGap(50, 50, 50))))
        );
        ServicesLayout.setVerticalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LbRoomManage1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnReloadService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBackService)
                    .addComponent(btnAddService)
                    .addComponent(btnDeleteService)
                    .addComponent(btnUpdateService))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Services, "card3");

        Invoices.setBackground(new java.awt.Color(255, 102, 0));

        LbRoomManage2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbRoomManage2.setText("Service Management");

        btnAddInvoice.setText("Add");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });

        btnDeleteInvoice.setText("Delete");
        btnDeleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInvoiceActionPerformed(evt);
            }
        });

        btnBackInvoice.setText("Back");
        btnBackInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackInvoiceActionPerformed(evt);
            }
        });

        btnUpdateInvoice.setText("Update");
        btnUpdateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInvoiceActionPerformed(evt);
            }
        });

        btnReloadInVoice.setText("Reload");
        btnReloadInVoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadInVoiceActionPerformed(evt);
            }
        });

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Type", "Describe", "Price", "Status"
            }
        ));
        jScrollPane3.setViewportView(tblInvoices);
        tblRooms.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblRooms.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblRooms.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblRooms.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblRooms.getColumnModel().getColumn(4).setPreferredWidth(130);

        javax.swing.GroupLayout InvoicesLayout = new javax.swing.GroupLayout(Invoices);
        Invoices.setLayout(InvoicesLayout);
        InvoicesLayout.setHorizontalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InvoicesLayout.createSequentialGroup()
                        .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(InvoicesLayout.createSequentialGroup()
                                .addComponent(btnReloadInVoice)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(InvoicesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LbRoomManage2)
                        .addGap(230, 230, 230))))
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnAddInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackInvoice)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InvoicesLayout.setVerticalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LbRoomManage2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReloadInVoice)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBackInvoice)
                    .addComponent(btnAddInvoice)
                    .addComponent(btnDeleteInvoice)
                    .addComponent(btnUpdateInvoice))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Invoices, "card4");

        jSplitPane1.setRightComponent(CardLayout_Management);
        CardLayout_Management.setLayout(new CardLayout());

        // Thêm các panel vào CardLayout với tên (key)
        CardLayout_Management.add(Rooms, "Rooms");
        CardLayout_Management.add(Services, "Services");
        CardLayout_Management.add(Invoices, "Invoices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Rooms");
    }//GEN-LAST:event_btnRoomManagementActionPerformed

    private void btnServiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Services");
    }//GEN-LAST:event_btnServiceManagementActionPerformed

    private void btnInvoiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Invoices");
        
    }//GEN-LAST:event_btnInvoiceManagementActionPerformed

    private void btnReloadRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadRoomActionPerformed
        // TODO add your handling code here:
        rooms.clear(); // Xoá dữ liệu cũ trong danh sách

        String sql = "SELECT * FROM DVPHONG";
        String url = "jdbc:oracle:thin:@localhost:1521:orcltdt"; // Thay đổi theo cấu hình của bạn
        String user = "java01";
        String password = "java01";
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Room room = new Room();
                //room.roomID = rs.getString("MADVP");
                room.setRoomID(rs.getString("MADVP"));
                //room.loaiPhong = rs.getString("LOAIPHONG");
                room.setLoaiPhong(rs.getString("LOAIPHONG"));
                //room.moTa = rs.getString("MOTA");
                room.setMoTa(rs.getString("MOTA"));
                //room.donGia = rs.getInt("DONGIA");
                room.setDonGia(rs.getInt("DONGIA"));
                //room.tinhTrang = rs.getString("TINHTRANG");
                room.setRoomID(rs.getString("TINHTRANG"));
                rooms.add(room);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }

        // Hiển thị lại dữ liệu lên JTable
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Room r : rooms) {
            model.addRow(new Object[] {
                r.getRoomID(),
                r.getLoaiPhong(),
                r.getMoTa(),
                r.getDonGia(),
                r.getTinhTrang()
            });
        }
    }//GEN-LAST:event_btnReloadRoomActionPerformed

    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed
        // TODO add your handling code here:
        UpdateRoomForm updateRoomForm = new UpdateRoomForm();
        updateRoomForm.setVisible(true);
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void btnBackRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackRoomActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRooms.getSelectedRow(); // lấy dòng được chọn

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xoá dòng khỏi bảng
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.removeRow(selectedRow);
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        AddRoomForm addRoomForm = new AddRoomForm();
        addRoomForm.setVisible(true);
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
        AddServiceForm addServiceForm = new AddServiceForm();
        addServiceForm.setVisible(true);
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblServices.getSelectedRow(); // lấy dòng được chọn

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xoá dòng khỏi bảng
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.removeRow(selectedRow);

    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnBackServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackServiceActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnBackServiceActionPerformed

    private void btnUpdateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServiceActionPerformed
        // TODO add your handling code here:
        UpdateServiceForm updateServiceForm = new UpdateServiceForm();
        updateServiceForm.setVisible(true);

    }//GEN-LAST:event_btnUpdateServiceActionPerformed

    private void btnReloadServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadServiceActionPerformed
        // TODO add your handling code here:
        services.clear(); // Xoá dữ liệu cũ trong danh sách

        String sql = "SELECT * FROM DVTIENICH";
        String url = "jdbc:oracle:thin:@localhost:1521:orcltdt"; // Thay đổi theo cấu hình của bạn
        String user = "java01";
        String password = "java01";
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Service service = new Service();                             
                service.setTenDV(rs.getString("TENDV"));               
                service.setMoTa(rs.getString("MOTA"));               
                service.setDonGia(rs.getInt("DONGIA"));
                service.setMaDV(rs.getString("MADVTI"));  
                services.add(service);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }

        // Hiển thị lại dữ liệu lên JTable
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Service se : services) {
            model.addRow(new Object[] {
                se.getMaDV(),
                se.getTenDV(),
                se.getMoTa(),
                se.getDonGia(),
                se.getTinhTrang()
            });
        }
        
    }//GEN-LAST:event_btnReloadServiceActionPerformed

    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        // TODO add your handling code here:
        AddInvoiceForm addInvoiceForm = new AddInvoiceForm();
        addInvoiceForm.setVisible(true);
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnDeleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteInvoiceActionPerformed

    private void btnBackInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackInvoiceActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackInvoiceActionPerformed

    private void btnUpdateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInvoiceActionPerformed
        // TODO add your handling code here:
        UpdateInvoiceForm updateInvoiceForm = new UpdateInvoiceForm();
        updateInvoiceForm.setVisible(true);
    }//GEN-LAST:event_btnUpdateInvoiceActionPerformed

    private void btnReloadInVoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadInVoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadInVoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardLayout_Management;
    private javax.swing.JPanel Invoices;
    private javax.swing.JLabel LbRoomManage;
    private javax.swing.JLabel LbRoomManage1;
    private javax.swing.JLabel LbRoomManage2;
    private javax.swing.JPanel Rooms;
    private javax.swing.JPanel Services;
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnBackInvoice;
    private javax.swing.JButton btnBackRoom;
    private javax.swing.JButton btnBackService;
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnInvoiceManagement;
    private javax.swing.JButton btnReloadInVoice;
    private javax.swing.JButton btnReloadRoom;
    private javax.swing.JButton btnReloadService;
    private javax.swing.JButton btnRoomManagement;
    private javax.swing.JButton btnServiceManagement;
    private javax.swing.JButton btnUpdateInvoice;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTable tblServices;
    // End of variables declaration//GEN-END:variables
}
