/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.dashboard_main;
// TranDuongTuan_27052025_Change_5:32
import hotelmanagement.add.AddInvoiceForm;
import hotelmanagement.add.AddRoomForm;
import hotelmanagement.add.AddServiceForm;
import hotelmanagement.entity.Current_User;
import hotelmanagement.entity.Invoice;
import hotelmanagement.entity.Room;
import hotelmanagement.entity.Service;
import hotelmanagement.entity.Customer;
import hotelmanagement.entity.Payout;
import hotelmanagement.entity.dba_connection;
import hotelmanagement.update.UpdateInvoiceForm;
import hotelmanagement.update.UpdateRoomForm;
import hotelmanagement.update.UpdateServiceForm;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;


public class DashboardForm extends javax.swing.JFrame {

    public ArrayList<Room> rooms = new ArrayList<>();
    public ArrayList<Service> services = new ArrayList<>();
    public ArrayList<Invoice> invoices = new ArrayList<>();
    public ArrayList<Customer> customers = new ArrayList<>();
    public ArrayList<Payout> list = new ArrayList<>();
    public DashboardForm() {       
        initComponents();
        setLocationRelativeTo(null);
        autoReloadRoom();
        autoReloadService();
        autoReloadInvoice();
        autoReloadCustomer();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        panelBtn = new javax.swing.JPanel();
        btnRoomManagement = new javax.swing.JButton();
        btnServiceManagement = new javax.swing.JButton();
        btnInvoiceManagement = new javax.swing.JButton();
        btnCustomerManagement = new javax.swing.JButton();
        btnPayCheckout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CardLayout_Management = new javax.swing.JPanel();
        CardPayCheckout = new javax.swing.JPanel();
        btnThanhtoan = new javax.swing.JButton();
        btnGiahan = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        pay_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sdt_txt = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        Rooms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        LbRoomManage = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        roomBtnPanel = new javax.swing.JPanel();
        btnAddRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnBackRoom = new javax.swing.JButton();
        btnUpdateRoom = new javax.swing.JButton();
        Services = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        LbRoomManage1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        serviceBtnPanel = new javax.swing.JPanel();
        btnAddService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        btnBackService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();
        Service_invoice = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Invoices = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        LbRoomManage2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        invoiceBtnPanel = new javax.swing.JPanel();
        btnAddInvoice = new javax.swing.JButton();
        btnBackInvoice = new javax.swing.JButton();
        btnDeleteInvoice = new javax.swing.JButton();
        btnUpdateInvoice = new javax.swing.JButton();
        Customers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAddCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        btnBackCustomer = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);

        jPanel1.setBackground(new java.awt.Color(46, 121, 130));

        panelBtn.setBackground(new java.awt.Color(46, 121, 130));
        panelBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnRoomManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRoomManagement.setText("Rooms");
        btnRoomManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManagementActionPerformed(evt);
            }
        });

        btnServiceManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnServiceManagement.setText("Services");
        btnServiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceManagementActionPerformed(evt);
            }
        });

        btnInvoiceManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInvoiceManagement.setText("Invoices");
        btnInvoiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceManagementActionPerformed(evt);
            }
        });

        btnCustomerManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCustomerManagement.setText("Customers");
        btnCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagementActionPerformed(evt);
            }
        });

        btnPayCheckout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPayCheckout.setText("Pay & Checkout");
        btnPayCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayCheckout)
                    .addComponent(btnInvoiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnServiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnInvoiceManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnPayCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager_icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        CardLayout_Management.setLayout(new java.awt.CardLayout());

        CardPayCheckout.setBackground(new java.awt.Color(255, 255, 255));

        btnThanhtoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThanhtoan.setText("Checkout");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        btnGiahan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnGiahan.setText("Extension");
        btnGiahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiahanActionPerformed(evt);
            }
        });

        pay_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pay_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Invoice", "Room", "Describe", "Start Date", "End Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(pay_table);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("PAY & CHECKOUT");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("SDT: ");

        Sdt_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CardPayCheckoutLayout = new javax.swing.GroupLayout(CardPayCheckout);
        CardPayCheckout.setLayout(CardPayCheckoutLayout);
        CardPayCheckoutLayout.setHorizontalGroup(
            CardPayCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPayCheckoutLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel4))
            .addGroup(CardPayCheckoutLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(Sdt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch))
            .addGroup(CardPayCheckoutLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CardPayCheckoutLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(btnThanhtoan)
                .addGap(100, 100, 100)
                .addComponent(btnGiahan))
        );
        CardPayCheckoutLayout.setVerticalGroup(
            CardPayCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPayCheckoutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addGroup(CardPayCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Sdt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(CardPayCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhtoan)
                    .addComponent(btnGiahan)))
        );

        CardLayout_Management.add(CardPayCheckout, "card7");

        Rooms.setBackground(new java.awt.Color(255, 255, 255));

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Type", "Describe", "Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRooms);
        tblRooms.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblRooms.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblRooms.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblRooms.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblRooms.getColumnModel().getColumn(4).setPreferredWidth(130);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(5, 5));

        LbRoomManage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbRoomManage.setText("Room Management");

        roomBtnPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnAddRoom.setText("Add");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setText("Delete");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnBackRoom.setText("Back");
        btnBackRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRoomActionPerformed(evt);
            }
        });

        btnUpdateRoom.setText("Update");
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roomBtnPanelLayout = new javax.swing.GroupLayout(roomBtnPanel);
        roomBtnPanel.setLayout(roomBtnPanelLayout);
        roomBtnPanelLayout.setHorizontalGroup(
            roomBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomBtnPanelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        roomBtnPanelLayout.setVerticalGroup(
            roomBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomBtnPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(roomBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRoom)
                    .addComponent(btnDeleteRoom)
                    .addComponent(btnBackRoom)
                    .addComponent(btnUpdateRoom))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RoomsLayout = new javax.swing.GroupLayout(Rooms);
        Rooms.setLayout(RoomsLayout);
        RoomsLayout.setHorizontalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomsLayout.createSequentialGroup()
                        .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(RoomsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(jScrollPane1))))
                        .addContainerGap())
                    .addGroup(RoomsLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(roomBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
            .addGroup(RoomsLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(LbRoomManage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RoomsLayout.setVerticalGroup(
            RoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsLayout.createSequentialGroup()
                .addComponent(LbRoomManage)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(roomBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Rooms, "card2");

        Services.setBackground(new java.awt.Color(255, 255, 255));

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Type", "Describe", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblServices);
        tblServices.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblServices.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblServices.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblServices.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblServices.getColumnModel().getColumn(4).setPreferredWidth(130);

        LbRoomManage1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbRoomManage1.setText("Service Management");

        serviceBtnPanel.setBackground(new java.awt.Color(255, 255, 255));
        serviceBtnPanel.setPreferredSize(new java.awt.Dimension(484, 68));

        btnAddService.setText("Add");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnDeleteService.setText("Delete");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        btnBackService.setText("Back");
        btnBackService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackServiceActionPerformed(evt);
            }
        });

        btnUpdateService.setText("Update");
        btnUpdateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serviceBtnPanelLayout = new javax.swing.GroupLayout(serviceBtnPanel);
        serviceBtnPanel.setLayout(serviceBtnPanelLayout);
        serviceBtnPanelLayout.setHorizontalGroup(
            serviceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceBtnPanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateService, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteService, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackService, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        serviceBtnPanelLayout.setVerticalGroup(
            serviceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceBtnPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(serviceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddService)
                    .addComponent(btnUpdateService)
                    .addComponent(btnDeleteService)
                    .addComponent(btnBackService))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ServicesLayout = new javax.swing.GroupLayout(Services);
        Services.setLayout(ServicesLayout);
        ServicesLayout.setHorizontalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServicesLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(serviceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(ServicesLayout.createSequentialGroup()
                        .addGroup(ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbRoomManage1)
                .addGap(260, 260, 260))
        );
        ServicesLayout.setVerticalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LbRoomManage1)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(serviceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Services, "card3");

        Service_invoice.setPreferredSize(new java.awt.Dimension(1024, 811));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("SERVICE INVOICE ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Invoice", "Service Id", "Service name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Total: ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Pay");

        javax.swing.GroupLayout Service_invoiceLayout = new javax.swing.GroupLayout(Service_invoice);
        Service_invoice.setLayout(Service_invoiceLayout);
        Service_invoiceLayout.setHorizontalGroup(
            Service_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Service_invoiceLayout.createSequentialGroup()
                .addGroup(Service_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Service_invoiceLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel6))
                    .addGroup(Service_invoiceLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(Service_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Service_invoiceLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(514, 514, 514)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        Service_invoiceLayout.setVerticalGroup(
            Service_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Service_invoiceLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Service_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Service_invoice, "card7");

        Invoices.setBackground(new java.awt.Color(255, 255, 255));

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice ID", "Customer ID", "Room ID", "Service ID", "Feedback ID", "Staff ID", "Day Created", "Day Started", "Day Ended", "Day Paid", "Total", "Payment Status", "Amount"
            }
        ));
        jScrollPane4.setViewportView(tblInvoices);
        tblInvoices.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblInvoices.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblInvoices.getColumnModel().getColumn(6).setPreferredWidth(150);
        tblInvoices.getColumnModel().getColumn(7).setPreferredWidth(150);
        tblInvoices.getColumnModel().getColumn(8).setPreferredWidth(150);
        tblInvoices.getColumnModel().getColumn(9).setPreferredWidth(150);
        tblInvoices.getColumnModel().getColumn(10).setPreferredWidth(120);
        tblInvoices.getColumnModel().getColumn(11).setPreferredWidth(120);
        tblInvoices.getColumnModel().getColumn(12).setPreferredWidth(120);
        jScrollPane3.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(5, 5));

        LbRoomManage2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbRoomManage2.setText("Invoice Management");

        invoiceBtnPanel.setBackground(new java.awt.Color(255, 255, 255));
        invoiceBtnPanel.setForeground(new java.awt.Color(60, 63, 65));
        invoiceBtnPanel.setPreferredSize(new java.awt.Dimension(484, 68));

        btnAddInvoice.setText("Add");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });

        btnBackInvoice.setText("Back");
        btnBackInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackInvoiceActionPerformed(evt);
            }
        });

        btnDeleteInvoice.setText("Delete");
        btnDeleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInvoiceActionPerformed(evt);
            }
        });

        btnUpdateInvoice.setText("Update");
        btnUpdateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invoiceBtnPanelLayout = new javax.swing.GroupLayout(invoiceBtnPanel);
        invoiceBtnPanel.setLayout(invoiceBtnPanelLayout);
        invoiceBtnPanelLayout.setHorizontalGroup(
            invoiceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceBtnPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnAddInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        invoiceBtnPanelLayout.setVerticalGroup(
            invoiceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceBtnPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(invoiceBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInvoice)
                    .addComponent(btnDeleteInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackInvoice)
                    .addComponent(btnUpdateInvoice))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout InvoicesLayout = new javax.swing.GroupLayout(Invoices);
        Invoices.setLayout(InvoicesLayout);
        InvoicesLayout.setHorizontalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(InvoicesLayout.createSequentialGroup()
                        .addGroup(InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(InvoicesLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(invoiceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(LbRoomManage2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InvoicesLayout.setVerticalGroup(
            InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(LbRoomManage2)
                .addGap(44, 44, 44)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(invoiceBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jScrollPane4.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 5)); // 5 là chiều cao mới

        CardLayout_Management.add(Invoices, "card4");

        Customers.setBackground(new java.awt.Color(255, 255, 255));
        Customers.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Customer Management");

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Password", "Citizen ID", "Phone number", "Date of Birth", "Sex", "Address", "Email"
            }
        ));
        jScrollPane3.setViewportView(tblCustomers);
        tblCustomers.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblCustomers.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblCustomers.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblCustomers.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblCustomers.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblCustomers.getColumnModel().getColumn(4).setPreferredWidth(120);
        tblCustomers.getColumnModel().getColumn(5).setPreferredWidth(120);
        tblCustomers.getColumnModel().getColumn(6).setPreferredWidth(50);
        tblCustomers.getColumnModel().getColumn(7).setPreferredWidth(150);
        tblCustomers.getColumnModel().getColumn(8).setPreferredWidth(120);
        jScrollPane3.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(5, 5));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAddCustomer.setText("Add");

        btnUpdateCustomer.setText("Update");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Delete");

        btnBackCustomer.setText("Back");
        btnBackCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBackCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnUpdateCustomer)
                    .addComponent(btnDeleteCustomer)
                    .addComponent(btnBackCustomer))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CustomersLayout = new javax.swing.GroupLayout(Customers);
        Customers.setLayout(CustomersLayout);
        CustomersLayout.setHorizontalGroup(
            CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomersLayout.createSequentialGroup()
                .addGroup(CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomersLayout.createSequentialGroup()
                                .addGap(0, 197, Short.MAX_VALUE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7)))
                    .addGroup(CustomersLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(CustomersLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustomersLayout.setVerticalGroup(
            CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomersLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        CardLayout_Management.add(Customers, "card5");

        jSplitPane1.setRightComponent(CardLayout_Management);
        CardLayout_Management.setLayout(new CardLayout());

        // Thêm các panel vào CardLayout với tên (key)
        CardLayout_Management.add(Rooms, "Rooms");
        CardLayout_Management.add(Services, "Services");
        CardLayout_Management.add(Invoices, "Invoices");
        CardLayout_Management.add(Customers, "Customers");
        CardLayout_Management.add(CardPayCheckout, "Pay & Checkout");
        CardLayout_Management.add(Service_invoice,"");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Rooms");
    }//GEN-LAST:event_btnRoomManagementActionPerformed

    private void btnServiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Services");
    }//GEN-LAST:event_btnServiceManagementActionPerformed

    private void btnInvoiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Invoices");
        
    }//GEN-LAST:event_btnInvoiceManagementActionPerformed


    
    private void autoReloadRoom(){
        rooms.clear(); // Xoá dữ liệu cũ trong danh sách

        String sql = "SELECT * FROM DVPHONG";
        dba_connection connect = new dba_connection();
        try {
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Room room = new Room();
                //room.roomID = rs.getString("MADVP");
                room.setRoomID(rs.getString("MADVP"));
                //room.loaiPhong = rs.getString("LOAIPHONG");
                room.setLoaiPhong(rs.getString("LOAIPHONG"));
                //room.moTa = rs.getString("MOTA");
                room.setMoTa(rs.getString("MOTA"));
                //room.donGia = rs.getInt("DONGIA");
                room.setDonGia(rs.getInt("DONGIA"));
                //room.tinhTrang = rs.getString("TINHTRANG");
                room.setTinhTrang(rs.getString("TINHTRANG"));
                rooms.add(room);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }

        // Hiển thị lại dữ liệu lên JTable
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Room r : rooms) {
            model.addRow(new Object[] {
                r.getRoomID(),
                r.getLoaiPhong(),
                r.getMoTa(),
                r.getDonGia(),
                r.getTinhTrang()
            });
        }
    }
    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed
        // TODO add your handling code here:
        UpdateRoomForm updateRoomForm = new UpdateRoomForm();
        updateRoomForm.setVisible(true);
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void btnBackRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRoomActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackRoomActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRooms.getSelectedRow(); // lấy dòng được chọn

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xoá dòng khỏi bảng
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.removeRow(selectedRow);
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        AddRoomForm addRoomForm = new AddRoomForm();
        addRoomForm.setVisible(true);
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
        AddServiceForm addServiceForm = new AddServiceForm();
        addServiceForm.setVisible(true);
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblServices.getSelectedRow(); // lấy dòng được chọn

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xoá dòng khỏi bảng
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.removeRow(selectedRow);

    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnBackServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackServiceActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnBackServiceActionPerformed

    private void btnUpdateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServiceActionPerformed
        // TODO add your handling code here:
        UpdateServiceForm updateServiceForm = new UpdateServiceForm();
        updateServiceForm.setVisible(true);

    }//GEN-LAST:event_btnUpdateServiceActionPerformed
    
    private void autoReloadService(){
        //services.clear(); // Xoá dữ liệu cũ trong danh sách
        String sql = "SELECT * FROM DVTIENICH";
        dba_connection connect = new dba_connection();
       
        try {
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Service service = new Service();
                service.setMaDV(rs.getString("MADVTI"));
                service.setTenDV(rs.getString("TENDVTI"));               
                service.setMoTa(rs.getString("MOTA"));               
                service.setDonGia(rs.getInt("DONGIA"));
                service.setTinhTrang(rs.getString("TINHTRANG"));  
                services.add(service);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }

        // Hiển thị lại dữ liệu lên JTable
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Service se : services) {
            model.addRow(new Object[] {
                se.getMaDV(),
                se.getTenDV(),
                se.getMoTa(),
                se.getDonGia(),
                se.getTinhTrang()
            });
        }
    }
    
    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        // TODO add your handling code here:
        AddInvoiceForm addInvoiceForm = new AddInvoiceForm();
        addInvoiceForm.setVisible(true);
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnDeleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInvoiceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInvoices.getSelectedRow(); // lấy dòng được chọn

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xoá dòng khỏi bảng
        DefaultTableModel model = (DefaultTableModel) tblInvoices.getModel();
        model.removeRow(selectedRow);

    }//GEN-LAST:event_btnDeleteInvoiceActionPerformed

    private void btnBackInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackInvoiceActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackInvoiceActionPerformed

    private void btnUpdateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInvoiceActionPerformed
        // TODO add your handling code here:
        UpdateInvoiceForm updateInvoiceForm = new UpdateInvoiceForm();
        updateInvoiceForm.setVisible(true);
    }//GEN-LAST:event_btnUpdateInvoiceActionPerformed

    private void autoReloadInvoice(){
        //invoices.clear(); // Xoá dữ liệu cũ trong danh sách
        String sql = "SELECT * FROM HOADON";
        dba_connection connect = new dba_connection();
       
        try {
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                Invoice invoice = new Invoice();
                invoice.setMaHD(rs.getString("MAHD"));
                invoice.setMaKH(rs.getString("MAKH"));               
                invoice.setMaDVP(rs.getString("MADVP"));
                invoice.setMaDVTI(rs.getString("MADVTI"));
                invoice.setMaFB(rs.getString("MAFB"));
                invoice.setMaNV(rs.getString("NGUOIXACNHAN"));
                invoice.setNgayTao(rs.getString("NGAYTAO"));
                invoice.setNgayBD(rs.getString("NGAYBD"));
                invoice.setNgayKT(rs.getString("NGAYKT"));
                invoice.setNgayThanhToan(rs.getString("NGAYTHANHTOAN"));
                invoice.setTongTien(rs.getInt("TONGTIEN"));
                invoice.setTinhTrangTT(rs.getString("TINHTRANGTT"));
                invoice.setSLSD(rs.getInt("SLSD"));
                invoices.add(invoice);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }

        // Hiển thị lại dữ liệu lên JTable
        DefaultTableModel model = (DefaultTableModel) tblInvoices.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Invoice in : invoices) {
            model.addRow(new Object[] {
                in.getMaHD(),
                in.getMaKH(),
                in.getMaDVP(),
                in.getMaDVTI(),
                in.getMaFB(),
                in.getMaNV(),
                in.getNgayTao(),
                in.getNgayBD(),
                in.getNgayKT(),
                in.getNgayThanhToan(),
                in.getTongTien(),
                in.getTinhTrangTT(),
                in.getSLSD()
            });
        }
    }
    
    private void btnCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagementActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Customers");
    }//GEN-LAST:event_btnCustomerManagementActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnBackCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCustomerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackCustomerActionPerformed

    private void btnPayCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayCheckoutActionPerformed
        CardLayout cl = (CardLayout)(CardLayout_Management.getLayout());
        cl.show(CardLayout_Management, "Pay & Checkout");
        
    }//GEN-LAST:event_btnPayCheckoutActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed


    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnGiahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGiahanActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        dba_connection connect = new dba_connection();
        String sql_hoadon = "select MAHD, LOAIPHONG, MOTA, NGAYBD, NGAYKT, TINHTRANGTT FROM HOADON "
                    + "JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH "
                    + "JOIN DVPHONG ON HOADON.MADVP = DVPHONG.MADVP "                    
                    + "WHERE KHACHHANG.SDT = '" + Sdt_txt.getText() + "'";    
        
        try {
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);
            PreparedStatement pst = null;
            pst = con.prepareStatement(sql_hoadon);

            ResultSet rs2 = pst.executeQuery();
            while(rs2.next()){
                Payout pay = new Payout();
                pay.setMahd(rs2.getString("MAHD"));
                pay.setLoaiphong(rs2.getString("LOAIPHONG"));                
                pay.setNgaybd(rs2.getString("NGAYBD"));
                pay.setNgaykt(rs2.getString("NGAYKT"));
                pay.setTinhtrang(rs2.getString("TINHTRANGTT"));
                pay.setTenphong(rs2.getString("MOTA"));
                list.add(pay);
            }

            DefaultTableModel table =  (DefaultTableModel) pay_table.getModel();
            table.setRowCount(0);

            for(Payout p: list){
                table.addRow(new Object[]{
                    p.mahd,
                    p.loaiphong,
                    p.tenphong,
                    p.ngaybatdau,
                    p.ngayketthuc,
                    p.tinhtrangtt
                });
            }
           
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DashboardClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void autoReloadCustomer(){
        String sql = "SELECT * FROM KHACHHANG";
        dba_connection connect = new dba_connection();
       
        try {
            Class.forName(connect.driver);
            Connection con = DriverManager.getConnection(connect.url, connect.username, connect.password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                Customer customer = new Customer();
                customer.setCustomerID(rs.getString("MAKH"));
                customer.setName(rs.getString("HOTEN"));
                customer.setPassword(rs.getString("PASSWORD"));
                customer.setCitizenID(rs.getString("CCCD"));
                customer.setPhoneNumber(rs.getString("SDT"));
                customer.setDateOfBirth(rs.getDate("NGAYSINH")); // Use getDate for DATE type
                customer.setGender(rs.getString("GIOITINH"));
                customer.setAddress(rs.getString("DIACHI"));
                customer.setEmail(rs.getString("EMAIL"));
                customers.add(customer);
            }
        }
        catch (SQLException | ClassNotFoundException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi load dữ liệu phòng: " + ex.getMessage());
        }
        
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0); // Xoá hết dữ liệu cũ trên bảng

        for (Customer cus : customers) {
            model.addRow(new Object[] {
                cus.getCustomerID(),
                cus.getName(),
                cus.getPassword(),
                cus.getCitizenID(),
                cus.getPhoneNumber(),
                cus.getDateOfBirth(),
                cus.getGender(),
                cus.getAddress(),
                cus.getEmail()
            });
    }
    /**
     * @param args the command line arguments
     */
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardLayout_Management;
    private javax.swing.JPanel CardPayCheckout;
    private javax.swing.JPanel Customers;
    private javax.swing.JPanel Invoices;
    private javax.swing.JLabel LbRoomManage;
    private javax.swing.JLabel LbRoomManage1;
    private javax.swing.JLabel LbRoomManage2;
    private javax.swing.JPanel Rooms;
    private javax.swing.JTextField Sdt_txt;
    private javax.swing.JPanel Service_invoice;
    private javax.swing.JPanel Services;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnBackCustomer;
    private javax.swing.JButton btnBackInvoice;
    private javax.swing.JButton btnBackRoom;
    private javax.swing.JButton btnBackService;
    private javax.swing.JButton btnCustomerManagement;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnDeleteInvoice;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnGiahan;
    private javax.swing.JButton btnInvoiceManagement;
    private javax.swing.JButton btnPayCheckout;
    private javax.swing.JButton btnRoomManagement;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnServiceManagement;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnUpdateInvoice;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.JPanel invoiceBtnPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTable pay_table;
    private javax.swing.JPanel roomBtnPanel;
    private javax.swing.JPanel serviceBtnPanel;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTable tblServices;
    // End of variables declaration//GEN-END:variables
}
